name: flutter_advanced_calendar_example
description: Demonstrates how to use the flutter_advanced_calendar plugin.

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_advanced_calendar:
    path: ../
  intl: ^0.19.0

flutter:
  uses-material-design: true
